apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeserver-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-nodeserver
  ports:
    - port: 9090
      targetPort: 9090